"""Obsidian vault export utilities for dwriter."""

import os
import re
from datetime import datetime
from pathlib import Path

from ..config import ObsidianConfig


def strip_rich_markup(text: str) -> str:
    """Strips Rich color/style markup while preserving Markdown structure.

    Args:
        text: The text containing Rich markup (e.g., [#cba6f7], [bold]).

    Returns:
        Clean text with Rich tags removed.
    """
    # Pattern to target Rich syntax: [bold], [#cba6f7], [dim], [/], [bold #cba6f7], [/#23c76b], etc.  # noqa: E501
    # It avoids stripping [[wikilinks]] by ensuring we don't match if it's a double bracket.  # noqa: E501
    # Matches a '[' NOT preceded by '[', followed by optional '/',
    # then optionally either a style word (with optional attributes) or a hex color,
    # followed by ']' NOT followed by ']'.
    rich_tag_pattern = r"(?<!\[)\[/?(?:[a-zA-Z]+(?: [a-zA-Z0-9#_]*)*|#[a-fA-F0-9]{6})?\](?!\])"  # noqa: E501
    return re.sub(rich_tag_pattern, "", text)


def render_ai_report_note(
    title: str,
    report_kind: str,
    content: str,
    date: datetime,
    range_label: str | None = None,
) -> str:
    """Produces a complete Obsidian note string for an AI report.

    Args:
        title: The note title.
        report_kind: Kind of report (standup, weekly-retro, burnout-check, catch-up).
        content: The Markdown content of the report.
        date: The date of the report.
        range_label: Optional range label for Catch Up reports.

    Returns:
        A formatted Markdown string with YAML frontmatter.
    """
    frontmatter = [
        "---",
        f"date: {date.strftime('%Y-%m-%d')}",
        "type: ai-report",
        f"report-kind: {report_kind}",
        "source: dwriter-2nd-brain",
    ]
    if range_label:
        frontmatter.append(f'range: "{range_label}"')
    frontmatter.append("---\n")

    body = [
        f"# {title}",
        "",
        f"> *Generated by dwriter 2nd-Brain on {date.strftime('%Y-%m-%d at %H:%M')}*",
        "",
        content,
        "",
        "---",
        "*Exported from dwriter*",
    ]

    return "\n".join(frontmatter) + "\n".join(body)


def render_review_note(
    content: str, start_date: datetime, end_date: datetime, num_days: int
) -> str:
    """Produces a complete Obsidian note string for a period review.

    Args:
        content: The Markdown content of the review.
        start_date: Start of the review period.
        end_date: End of the review period.
        num_days: Number of days in the period.

    Returns:
        A formatted Markdown string with YAML frontmatter.
    """
    frontmatter = [
        "---",
        f"period-start: {start_date.strftime('%Y-%m-%d')}",
        f"period-end: {end_date.strftime('%Y-%m-%d')}",
        f"days: {num_days}",
        "type: period-review",
        "source: dwriter-review",
        "---\n",
    ]

    body = [
        f"# {num_days}-Day Review · {start_date.strftime('%Y-%m-%d')} – {end_date.strftime('%Y-%m-%d')}",  # noqa: E501
        "",
        content,
        "",
        "---",
        "*Exported from dwriter*",
    ]

    return "\n".join(frontmatter) + "\n".join(body)


def get_note_path(
    config: ObsidianConfig, note_type: str, date: datetime, title: str = ""
) -> Path:
    """Maps note type to vault subfolder and constructs the full path.

    Args:
        config: Obsidian configuration.
        note_type: The type of note (standup, weekly-retro,
            burnout-check, catch-up, review).
        date: The date for the filename.
        title: Optional title for the filename.

    Returns:
        The full Path to the note file.
    """
    if not config.vault_path:
        raise ValueError("Obsidian vault_path is not configured.")

    vault_root = Path(config.vault_path)

    if note_type == "review":
        folder = vault_root / config.reviews_folder
    else:
        folder = vault_root / config.ai_reports_folder

    # Sanitize title for filesystem safety
    # Strip characters not valid in filenames: / \ : * ? " < > |
    safe_title = re.sub(r'[\\/:*?"<>|]', "", title).strip()

    filename = f"{date.strftime('%Y-%m-%d')} — {safe_title}.md"
    return folder / filename


def write_note(path: Path, content: str) -> None:
    """Atomic write of note content to the specified path.

    Args:
        path: The target path.
        content: The string content to write.
    """
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = path.with_suffix(".tmp.md")
        tmp_path.write_text(content, encoding="utf-8")
        os.replace(tmp_path, path)
    except OSError as e:
        raise OSError(f"Failed to write Obsidian note to {path}: {e}") from e


def obsidian_is_configured(config: ObsidianConfig) -> bool:
    """Checks if Obsidian export is properly configured.

    Args:
        config: Obsidian configuration.

    Returns:
        True if vault_path is set and exists.
    """
    if not config.vault_path:
        return False
    return Path(config.vault_path).exists()
