"""Unit tests for Obsidian export module."""

import os
from datetime import datetime
from pathlib import Path

import pytest
import tomlkit

from dwriter.config import ObsidianConfig
from dwriter.export.obsidian import (
    get_note_path,
    obsidian_is_configured,
    render_ai_report_note,
    render_review_note,
    strip_rich_markup,
    write_note,
)


def test_strip_rich_markup():
    """Test stripping Rich markup while preserving Markdown and wikilinks."""
    assert strip_rich_markup("[#23c76b]text[/#23c76b]") == "text"
    assert strip_rich_markup("[bold #cba6f7]text[/]") == "text"
    assert strip_rich_markup("[dim]text[/dim]") == "text"
    assert strip_rich_markup("Regular text") == "Regular text"
    
    # Preserve wikilinks
    assert strip_rich_markup("[[wikilink]]") == "[[wikilink]]"
    assert strip_rich_markup("Check [[ProjectX]] for details") == "Check [[ProjectX]] for details"
    
    # Preserve hashtags
    assert strip_rich_markup("#hashtag") == "#hashtag"
    assert strip_rich_markup("Fixing #bug in &dwriter") == "Fixing #bug in &dwriter"
    
    # Compound and block characters
    assert strip_rich_markup("[bold #a6e3a1]█░[/]") == "█░"


def test_render_ai_report_note():
    """Test AI report note rendering with YAML frontmatter."""
    title = "Weekly Retro"
    report_kind = "weekly-retro"
    content = "This was a good week."
    date = datetime(2026, 4, 11, 14, 30)
    
    note = render_ai_report_note(title, report_kind, content, date)
    
    # Basic structure
    assert note.startswith("---")
    assert content in note
    assert "# Weekly Retro" in note
    assert "Generated by dwriter 2nd-Brain on 2026-04-11 at 14:30" in note
    
    # Check frontmatter strings directly to avoid YAML dependency in tests
    assert "date: 2026-04-11" in note
    assert "type: ai-report" in note
    assert "report-kind: weekly-retro" in note
    assert "source: dwriter-2nd-brain" in note


def test_render_ai_report_note_with_range():
    """Test AI report note rendering with range label (Catch Up)."""
    title = "Catch Up"
    report_kind = "catch-up"
    content = "Catching up on work."
    date = datetime(2026, 4, 11)
    range_label = "2026-04-01 to 2026-04-07"
    
    note = render_ai_report_note(title, report_kind, content, date, range_label=range_label)
    
    assert f'range: "{range_label}"' in note


def test_render_review_note():
    """Test review note rendering with YAML frontmatter."""
    content = "Summary of past days."
    start_date = datetime(2026, 4, 1)
    end_date = datetime(2026, 4, 5)
    num_days = 5
    
    note = render_review_note(content, start_date, end_date, num_days)
    
    assert note.startswith("---")
    assert content in note
    assert "# 5-Day Review" in note
    
    assert "period-start: 2026-04-01" in note
    assert "period-end: 2026-04-05" in note
    assert "days: 5" in note
    assert "type: period-review" in note
    assert "source: dwriter-review" in note


def test_get_note_path(tmp_path):
    """Test note path generation and sanitization."""
    config = ObsidianConfig(
        vault_path=str(tmp_path),
        ai_reports_folder="Reports",
        reviews_folder="Log/Reviews"
    )
    date = datetime(2026, 4, 11)
    
    # AI Report path
    path = get_note_path(config, "standup", date, "Daily Standup")
    assert path == tmp_path / "Reports" / "2026-04-11 — Daily Standup.md"
    
    # Review path
    path = get_note_path(config, "review", date, "5-Day Review")
    assert path == tmp_path / "Log/Reviews" / "2026-04-11 — 5-Day Review.md"
    
    # Sanitization
    path = get_note_path(config, "standup", date, "Project: Work/Life?")
    assert "Project WorkLife" in path.name
    assert ":" not in path.name
    assert "/" not in path.name
    assert "?" not in path.name


def test_write_note(tmp_path):
    """Test atomic note writing."""
    target_path = tmp_path / "subdir" / "note.md"
    content = "Hello Obsidian"
    
    write_note(target_path, content)
    
    assert target_path.exists()
    assert target_path.read_text(encoding="utf-8") == content
    assert not target_path.with_suffix(".tmp.md").exists()


def test_obsidian_is_configured(tmp_path):
    """Test configuration validation."""
    # Not set
    config = ObsidianConfig(vault_path=None)
    assert not obsidian_is_configured(config)
    
    # Nonexistent
    config = ObsidianConfig(vault_path=str(tmp_path / "missing"))
    assert not obsidian_is_configured(config)
    
    # Valid
    config = ObsidianConfig(vault_path=str(tmp_path))
    assert obsidian_is_configured(config)

